version: '3.8'

services:

  ecommerce-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=ecommerce_user
      - SPRING_DATASOURCE_PASSWORD=passworduntudkecommerce1234)(*
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=ecommerce_user
      - POSTGRES_PASSWORD=passworduntudkecommerce1234)(*
    volumes:
      - ecommerce_data:/var/lib/postgresql/data

volumes:
  ecommerce_data:
  redis_data: